export const octKeysInit = [
  { 'name': 'A0', 'using': false, color: '#B8D8D8' },
  { 'name': 'B0', 'using': false, color: '#B8D8D8' },
  { 'name': 'A1', 'using': false, color: '#7A9E9F' },
  { 'name': 'A2', 'using': false, color: '#7A9E9F' },
  { 'name': 'A3', 'using': false, color: '#7A9E9F' },
  { 'name': 'A4', 'using': false, color: '#7A9E9F' },
  { 'name': 'A5', 'using': false, color: '#7A9E9F' },
  { 'name': 'A6', 'using': false, color: '#7A9E9F' },
  { 'name': 'A7', 'using': false, color: '#7A9E9F' },
  { 'name': 'A8', 'using': false, color: '#7A9E9F' },
  { 'name': 'A9', 'using': false, color: '#7A9E9F' },

  { 'name': 'B1', 'using': false, color: '#4F6367' },
  { 'name': 'B2', 'using': false, color: '#4F6367' },
  { 'name': 'B3', 'using': false, color: '#4F6367' },
  { 'name': 'B4', 'using': false, color: '#4F6367' },
  { 'name': 'B5', 'using': false, color: '#4F6367' },
  { 'name': 'B6', 'using': false, color: '#4F6367' },
  { 'name': 'B7', 'using': false, color: '#4F6367' },
  { 'name': 'B8', 'using': false, color: '#4F6367' },
  { 'name': 'B9', 'using': false, color: '#4F6367' },

  { 'name': 'C1', 'using': false, color: '#EEF5DB' },
  { 'name': 'C2', 'using': false, color: '#EEF5DB' },
  { 'name': 'C3', 'using': false, color: '#EEF5DB' },
  { 'name': 'C4', 'using': false, color: '#EEF5DB' },
  { 'name': 'C5', 'using': false, color: '#EEF5DB' },
  { 'name': 'C6', 'using': false, color: '#EEF5DB' },
  { 'name': 'C7', 'using': false, color: '#EEF5DB' },
  { 'name': 'C8', 'using': false, color: '#EEF5DB' },
  { 'name': 'C9', 'using': false, color: '#EEF5DB' },

  { 'name': 'D1', 'using': false, color: '#FE5F55' },
  { 'name': 'D2', 'using': false, color: '#FE5F55' },
  { 'name': 'D3', 'using': false, color: '#FE5F55' },
  { 'name': 'D4', 'using': false, color: '#FE5F55' },
  { 'name': 'D5', 'using': false, color: '#FE5F55' },
  { 'name': 'D6', 'using': false, color: '#FE5F55' },
  { 'name': 'D7', 'using': false, color: '#FE5F55' },
  { 'name': 'D8', 'using': false, color: '#FE5F55' },
  { 'name': 'D9', 'using': false, color: '#FE5F55' },

  { 'name': 'E1', 'using': false, color: '#D6FF79' },
  { 'name': 'E2', 'using': false, color: '#D6FF79' },
  { 'name': 'E3', 'using': false, color: '#D6FF79' },
  { 'name': 'E4', 'using': false, color: '#D6FF79' },
  { 'name': 'E5', 'using': false, color: '#D6FF79' },
  { 'name': 'E6', 'using': false, color: '#D6FF79' },
  { 'name': 'E7', 'using': false, color: '#D6FF79' },
  { 'name': 'E8', 'using': false, color: '#D6FF79' },
  { 'name': 'E9', 'using': false, color: '#D6FF79' },

  { 'name': 'F1', 'using': false, color: '#B0FF92' },
  { 'name': 'F2', 'using': false, color: '#B0FF92' },
  { 'name': 'F3', 'using': false, color: '#B0FF92' },
  { 'name': 'F4', 'using': false, color: '#B0FF92' },
  { 'name': 'F5', 'using': false, color: '#B0FF92' },
  { 'name': 'F6', 'using': false, color: '#B0FF92' },
  { 'name': 'F7', 'using': false, color: '#B0FF92' },
  { 'name': 'F8', 'using': false, color: '#B0FF92' },
  { 'name': 'F9', 'using': false, color: '#B0FF92' },

  { 'name': 'G1', 'using': false, color: '#A09BE7' },
  { 'name': 'G2', 'using': false, color: '#A09BE7' },
  { 'name': 'G3', 'using': false, color: '#A09BE7' },
  { 'name': 'G4', 'using': false, color: '#A09BE7' },
  { 'name': 'G5', 'using': false, color: '#A09BE7' },
  { 'name': 'G6', 'using': false, color: '#A09BE7' },
  { 'name': 'G7', 'using': false, color: '#A09BE7' },
  { 'name': 'G8', 'using': false, color: '#A09BE7' },
  { 'name': 'G9', 'using': false, color: '#A09BE7' },
];